###
 #  _____                 _   _       
 # |  __ \               | | (_)      
 # | |  | | ___  _ __ ___| |  _  ___  
 # | |  | |/ _ \| '__/ _ \ | | |/ _ \ 
 # | |__| | (_) | | |  __/ |_| | (_) |
 # |_____/ \___/|_|  \___|_(_)_|\___/                                 
 #
 # Description: Installs a complete Magento 2 installation in travis and validates the APIs
 # Author: Bob van Luijt
 #
###

dist: trusty

sudo: required

  
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
  
before_install:
  # Install proxy
  - sudo apt-get update
  - sudo apt-get install unzip -qq -y
  - cd ~ 
  - wget https://github.com/bobvanluijt/Docker-multi-wordpress-google-cloud/archive/master.zip
  - unzip master.zip
  - rm master.zip
  - cd Docker-multi-wordpress-google-cloud-master
  - sudo chmod +x ./*.sh
  # proxy-setup.sh is here 
  - sudo printf 'localhost\n\n1\n' | ./proxy-setup.sh
  # Run the installer script
  - ./container-setup.sh --website test.com --accessurl www.test.com --dbhost localhost --dbname test --dbuser test --dbpass test567 --title Example --adminemail test@test.com --adminuser admin --adminpass test123