version: "2"
services:
    nginx:
        build: ./Dorel-Dockerfiles/wordpress-nginx
        expose:
            - "80"
        depends_on:
            - fpm
        links:
            - fpm
        container_name: wordpress-nginx
        args:
            - site_title=Example
            - admin_email=bob@kubrickolo.gy
            - site_url=www.testcase001.com
            - admin_user=admin
            - admin_pass=qwerty
            - ssl_domain=www.testcase001.com
            - dbname=testcase
            - dbuser=testcase
            - dbpass=testcase
            - dbhost=testcase
    fpm:
        build: ./Dorel-Dockerfiles/php-fpm
        expose:
            - "9000"
        container_name: fpm